FROM node:20-alpine as base
WORKDIR /app
COPY package*.json ./
RUN npm ci 
RUN npx ngcc --properties es2022 browser module main --first-only --create-ivy-entry-points
COPY . .
RUN npm run build
FROM nginx:stable-alpine
COPY --from=base /app/dist /usr/share/nginx/html
COPY /nginx.conf /etc/nginx/nginx.conf