version: '3.8'
services:
  messenger-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    environment:
      - DOCKER_ENV=true
    ports:
      - "18080:8080"
    volumes:
      - ./:/app
    depends_on:
      - database
    networks:
      - db-network

  database:
    image: postgres:latest
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_DB=ms-bot'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
    networks:
      - db-network

networks:
  db-network:
    driver: bridge