version: '3.8'
services:
  messenger-bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - MESSENGER_APP_VERIFICATION_TOKEN=token
      - MESSENGER_APP_SECRET_KEY=key
    ports:
      - "20174:8000"
    depends_on:
      - pg-db
    networks:
      - pg-network

  pg-db:
    image: postgres:alpine
    ports:
      - '30174:5432'
    environment:
      - 'POSTGRES_DB=ms-bot'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=admin'
    networks:
      - pg-network

networks:
  pg-network:
    driver: bridge